# FLASK APP SETTINGS
SECRET_KEY = ''
SQLALCHEMY_DATABASE_URI = ''

# MAIL CREDENTIALS
MAIL_SERVER = ''
MAIL_PORT = 587
MAIL_USE_TLS = True
MAIL_USE_SSL = False
MAIL_USERNAME = ''
MAIL_PASSWORD = ''
MAIL_ADDRESS = ''

# LDAP SETTINGS
LDAP_USER = ''
LDAP_PASS = ''
LDAP_SERVER = ''
AD_DOMAIN = ''
SEARCH_BASE = ''

# TOPDESK API
TOPDESK_API_URL = ''
TOPDESK_API_USER = ''
TOPDESK_API_PASS = ''

# PROXY
HTTP_PROXY = ''
