version: '3.8'

services:
  web:
    # Baut das Image aus dem Dockerfile im aktuellen Verzeichnis
    build: .
    # Startet den Container immer neu, es sei denn, er wird manuell gestoppt
    restart: unless-stopped
    # Lädt die Umgebungsvariablen aus einer .env-Datei
    env_file:
      - .env
    # Mappt den Port 5000 des Containers auf den Port 5000 Ihres Computers
    ports:
      - "5000:5000"
    # Mappt den Ordner für die generierten Raumschilder, damit sie auf Ihrem Computer erhalten bleiben
    volumes:
      - ./static/raumschilder:/app/static/raumschilder
    # Gibt dem Container einen eindeutigen Namen
    container_name: inventar-app
